<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Duende.IdentityServer.EntityFramework" Version="7.4.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(EntityFrameworkCoreVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="$(EntityFrameworkCoreVersion)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AlphaId.Migrations\AlphaId.Migrations.csproj" />
		<ProjectReference Include="..\AlphaId.EntityFramework\AlphaId.EntityFramework.csproj" />
		<ProjectReference Include="..\AlphaId.InitData\AlphaId.InitData.csproj" />
		<ProjectReference Include="..\AlphaId.TestingData\AlphaId.TestingData.csproj" />
		<ProjectReference Include="..\AlphaIdPlatform\AlphaIdPlatform.csproj" />
	</ItemGroup>
</Project>
