//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdSubjects {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdSubjects.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot change person name. 的本地化字符串。
        /// </summary>
        public static string CannotChangePersonName {
            get {
                return ResourceManager.GetString("CannotChangePersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duns Number 的本地化字符串。
        /// </summary>
        public static string DunsNumber {
            get {
                return ResourceManager.GetString("DunsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone number is already taken. 的本地化字符串。
        /// </summary>
        public static string DuplicatePhoneNumber {
            get {
                return ResourceManager.GetString("DuplicatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Female 的本地化字符串。
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid administrative code 的本地化字符串。
        /// </summary>
        public static string Invalid_administrative_code {
            get {
                return ResourceManager.GetString("Invalid administrative code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid region code. 的本地化字符串。
        /// </summary>
        public static string Invalid_region_code_ {
            get {
                return ResourceManager.GetString("Invalid region code.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone number is invalid. 的本地化字符串。
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid organization type. 的本地化字符串。
        /// </summary>
        public static string Invlid_organization_type_ {
            get {
                return ResourceManager.GetString("Invlid organization type.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are the last owner of this organization, for leaving organization, you must transfer you ownership to another member in this organization. 的本地化字符串。
        /// </summary>
        public static string LastOwnerCannotLeave {
            get {
                return ResourceManager.GetString("LastOwnerCannotLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legal Entity Identifier 的本地化字符串。
        /// </summary>
        public static string LegalEntityIdentifier {
            get {
                return ResourceManager.GetString("LegalEntityIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current password age is less then minimum passowrd age requirement. 的本地化字符串。
        /// </summary>
        public static string LessThenMinimumPasswordAge {
            get {
                return ResourceManager.GetString("LessThenMinimumPasswordAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Male 的本地化字符串。
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The membership already exists. 的本地化字符串。
        /// </summary>
        public static string MembershipExists {
            get {
                return ResourceManager.GetString("MembershipExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot reuse old passwords. 的本地化字符串。
        /// </summary>
        public static string ReuseOldPassword {
            get {
                return ResourceManager.GetString("ReuseOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified directory entry not found. 的本地化字符串。
        /// </summary>
        public static string Specified_directory_entry_not_found {
            get {
                return ResourceManager.GetString("Specified directory entry not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} can not be null or white space. 的本地化字符串。
        /// </summary>
        public static string StringIsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("StringIsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unified Social Credit Code 的本地化字符串。
        /// </summary>
        public static string UnifiedSocialCreditCode {
            get {
                return ResourceManager.GetString("UnifiedSocialCreditCode", resourceCulture);
            }
        }
    }
}
