SET IDENTITY_INSERT [dbo].[ApiScopes] ON 
SET IDENTITY_INSERT [dbo].[ApiScopes] OFF
SET IDENTITY_INSERT [dbo].[IdentityResources] ON 
SET IDENTITY_INSERT [dbo].[IdentityResources] OFF
SET IDENTITY_INSERT [dbo].[IdentityResourceClaims] ON 
SET IDENTITY_INSERT [dbo].[IdentityResourceClaims] OFF
SET IDENTITY_INSERT [dbo].[IdentityResourceProperties] ON 
SET IDENTITY_INSERT [dbo].[IdentityResourceProperties] OFF
SET IDENTITY_INSERT [dbo].[IdentityProviders] ON 
SET IDENTITY_INSERT [dbo].[IdentityProviders] OFF
SET IDENTITY_INSERT [dbo].[ApiResources] ON 
SET IDENTITY_INSERT [dbo].[ApiResources] OFF
SET IDENTITY_INSERT [dbo].[ApiResourceClaims] ON 
SET IDENTITY_INSERT [dbo].[ApiResourceClaims] OFF
SET IDENTITY_INSERT [dbo].[ApiResourceScopes] ON 
SET IDENTITY_INSERT [dbo].[ApiResourceScopes] OFF
SET IDENTITY_INSERT [dbo].[Clients] ON 
SET IDENTITY_INSERT [dbo].[Clients] OFF
SET IDENTITY_INSERT [dbo].[ClientGrantTypes] ON 
SET IDENTITY_INSERT [dbo].[ClientGrantTypes] OFF
SET IDENTITY_INSERT [dbo].[ClientPostLogoutRedirectUris] ON 
SET IDENTITY_INSERT [dbo].[ClientPostLogoutRedirectUris] OFF
SET IDENTITY_INSERT [dbo].[ClientRedirectUris] ON 
SET IDENTITY_INSERT [dbo].[ClientRedirectUris] OFF
SET IDENTITY_INSERT [dbo].[ClientScopes] ON 
SET IDENTITY_INSERT [dbo].[ClientScopes] OFF
SET IDENTITY_INSERT [dbo].[ClientSecrets] ON 
SET IDENTITY_INSERT [dbo].[ClientSecrets] OFF
SET IDENTITY_INSERT [dbo].[ClientCorsOrigins] ON
SET IDENTITY_INSERT [dbo].[ClientCorsOrigins] OFF
SET IDENTITY_INSERT [dbo].[ClientIdPRestrictions] ON
SET IDENTITY_INSERT [dbo].[ClientIdPRestrictions] OFF
SET IDENTITY_INSERT [dbo].[ClientProperties] ON
SET IDENTITY_INSERT [dbo].[ClientProperties] OFF
