# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build AlphaID

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore AlphaID.slnx -v m
      working-directory: src/AlphaID
    - name: Build
      run: dotnet build AlphaID.slnx --no-restore --configuration Release -v m
      working-directory: src/AlphaID
    - name: Install SQL Server LocalDB
      uses: potatoqualitee/mssqlsuite@v1.8
      with:
        # The apps to install
        install: localdb
    - name: Run database tool
      run: ./DatabaseTool.exe NonInteractive --environment Development
      working-directory: src/AlphaID/DatabaseTool/bin/Release/net10.0/
    - name: Test
      run: dotnet test AlphaID.slnx --no-build -v m
      working-directory: src/AlphaID