# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore AlphaID.sln
      working-directory: src/AlphaID
    - name: Build
      run: dotnet build --no-restore AlphaID.sln
      working-directory: src/AlphaID
    - name: Install SQL Server LocalDB
      uses: potatoqualitee/mssqlsuite@v1.8
      with:
        # The apps to install
        install: localdb
    - name: Run database tool
      run: ./DatabaseTool.exe NonInteractive --environment Development
      working-directory: src/AlphaID/DatabaseTool/bin/Debug/net8.0/
    - name: Test
      run: dotnet test --no-build --verbosity normal AlphaID.sln
      working-directory: src/AlphaID